<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2017 Modern Kernel
 */

namespace common\widgets;


use common\plugins\facebook\SDK;
use common\models\Setting;
use yii\base\Widget;
use yii\helpers\Html;

/**
 * Class Messenger
 * @package common\widgets
 */
class Messenger extends Widget
{
    public $appId = '';
    public $pageId = '';
    public $color = 'blue';
    public $size = 'large';

    public function init()
    {
        if (empty($this->appId)) {
            $this->appId = Setting::getValue('fbAppId');
        }
        if (empty($this->pageId)) {
            $this->pageId = Setting::getValue('fbPageId');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function run()
    {
        if (!empty($this->appId) && !empty($this->pageId)) {
            echo Html::tag('div', '', [
                'class' => 'fb-messengermessageus',
                'messenger_app_id' => $this->appId,
                'page_id' => $this->pageId,
                'color' => $this->color,
                'size' => $this->size
            ]);
            echo SDK::widget();
        }
    }


}