<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2016 Power Kernel
 */

namespace common\components;


use common\Core;
use nirvana\jsonld\JsonLDHelper;
use Yii;
use yii\web\Controller;

/**
 * Class MainController
 * @package common\components
 */
class MainController extends Controller
{
    /**
     * register metaTags and JsonLD info
     * @param array $data
     */
    public function registerMetaTagJsonLD($data = [])
    {
        $this->view->title = !empty($data['title']) ? $data['title'] : Yii::$app->name;

        if (!empty($data['jsonLd'])) {
            JsonLDHelper::add($data['jsonLd']);
        }
        if (!empty($data['metaTags'])) {
            foreach ($data['metaTags'] as $tag) {
                $this->view->registerMetaTag($tag);
            }
        }
    }

    /**
     * @inheritdoc
     * @param \yii\base\Action $action
     */
    public function beforeAction($action)
    {

        /* user no email, force add one */
        if (!Yii::$app->user->isGuest && Yii::$app->id=='app-frontend') {
            $user = Yii::$app->user->identity;
            if(empty($user->email)){
                if(!Core::checkMCA(null, 'account', ['email', 'email-confirm'])){
                    return Yii::$app->controller->redirect(Yii::$app->urlManager->createUrl(['account/email']));
                }
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub

    }
}