<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2017 Modern Kernel
 */

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%core_banner}}".
 *
 * @property integer $id
 * @property string $lang
 * @property string $title
 * @property string $text_content
 * @property string $text_style
 * @property string $banner_url
 * @property string $link_url
 * @property string $link_option
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 */
class Banner extends ActiveRecord
{


    const STATUS_ACTIVE = 10;
    const STATUS_INACTIVE = 20;


    /**
     * get status list
     * @param null $e
     * @return array
     */
    public static function getStatusOption($e = null)
    {
        $option = [
            self::STATUS_ACTIVE => Yii::t('app', 'Active'),
            self::STATUS_INACTIVE => Yii::t('app', 'Inactive'),
        ];
        if (is_array($e))
            foreach ($e as $i)
                unset($option[$i]);
        return $option;
    }

    /**
     * get status text
     * @return string
     */
    public function getStatusText()
    {
        $status = $this->status;
        $list = self::getStatusOption();
        if (!empty($status) && in_array($status, array_keys($list))) {
            return $list[$status];
        }
        return Yii::t('app', 'Unknown');
    }


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%core_banner}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'banner_url', 'status'], 'required'],
            [['text_content', 'text_style', 'lang'], 'string'],
            [['status', 'created_at', 'updated_at'], 'integer'],
            [['title', 'link_url', 'link_option'], 'string', 'max' => 255],
            [['banner_url', 'link_url'], 'url'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'lang' => Yii::t('app', 'Language'),
            'title' => Yii::t('app', 'Title'),
            'text_content' => Yii::t('app', 'Text'),
            'text_style' => Yii::t('app', 'Text Style'),
            'banner_url' => Yii::t('app', 'Banner URL'),
            'link_url' => Yii::t('app', 'Click URL'),
            'link_option' => Yii::t('app', 'Link Option'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        foreach ($this->attributes as $key => $value){
            if(empty($value)){
                $this->$key=null;
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
