<?php
/**
* @author Harry Tang <harry@powerkernel.com>
* @link https://powerkernel.com
* @copyright Copyright (c) 2016 Power Kernel
*/

namespace common\models;

use Yii;
use yii\db\ActiveRecord;
use yii\helpers\HtmlPurifier;

/**
 * This is the model class for table "{{%core_content}}".
 *
 * @property string $id
 * @property string $content
 */
class Content extends ActiveRecord
{


    const STATUS_ACTIVE = 10;
    const STATUS_INACTIVE = 20;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%core_content}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['content'], 'string'],
            [['id'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'content' => Yii::t('app', 'Content'),
        ];
    }

    /**
     * @inheritdoc
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        $this->content=HtmlPurifier::process($this->content);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    /**
     * @param $id
     * @return null|string
     */
    public static function getData($id){
        $c=self::findOne($id);
        if($c){
            return $c->content;
        }
        return null;
    }
}
