<?php

namespace common\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%core_page_id}}".
 *
 * @property string $id
 * @property integer $show_description
 * @property integer $show_update_date
 *
 * @property PageData[] $data
 * @property PageData $content
 */
class Page extends ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%core_page_id}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['show_description', 'show_update_date'], 'integer'],
            [['id'], 'string', 'max' => 100],
            //[['id'], 'match', 'patten'=>'/^[a-z]+$/i'],
            [['id'], 'unique'],
            [['id', 'show_description', 'show_update_date'], 'required', 'on' => ['create']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'show_description' => Yii::t('app', 'Show Description'),
            'show_update_date' => Yii::t('app', 'Show Update Date'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getData()
    {
        return $this->hasMany(PageData::className(), ['id_page' => 'id']);
    }


    /**
     * @return array|null|ActiveRecord
     */
    public function getContent()
    {
//        $data = $this->hasOne(PageData::className(), ['id_page' => 'id'])->where(['language' => Yii::$app->language]);
//        if ($data) {
//            $data = $this->hasOne(PageData::className(), ['id_page' => 'id']);
//        }
//        return $data;
        $data = PageData::find()->where(['id_page'=>$this->id, 'language' => Yii::$app->language, 'status'=>PageData::STATUS_ACTIVE])->one();
        if (!$data) {
            $data = PageData::find()->where(['id_page'=>$this->id, 'status'=>PageData::STATUS_ACTIVE])->one();
        }
        return $data;
    }



    /**
     * @return mixed|null
     */
    public function getPageTitle()
    {
        $data = PageData::find()->select('title')->where(['id_page'=>$this->id, 'language' => Yii::$app->language, 'status'=>PageData::STATUS_ACTIVE])->one();
        if (!$data) {
            $data = PageData::find()->select('title')->where(['id_page'=>$this->id, 'status'=>PageData::STATUS_ACTIVE])->one();
        }
        return isset($data)?$data->title:'unknown';
    }



    /**
     * @inheritdoc
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        $this->id=strtolower($this->id);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * get page title base on language
     * @param $id
     * @return mixed|null
     */
    public static function getTitle($id){
        $page=Page::findOne($id);
        if($page){
            return $page->getPageTitle();
        }
        return null;
    }


}
