<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2018 Power Kernel
 */

namespace frontend\modules\api\v1;


/**
 * API module definition class
 */
class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
