<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2018 Power Kernel
 */

namespace common\plugins\waves;

use yii\web\AssetBundle;

/**
 * Class WavesAsset
 * @package common\plugins\waves
 */
class WavesAsset extends AssetBundle
{
    public $sourcePath = '@common/plugins/waves/assets';

    public $js = [
        'waves.min.js',
    ];

    public $css = [
        'waves.css'
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $js='Waves.attach("a,button"); Waves.init();';

        \Yii::$app->view->registerJs($js);
    }
}
