<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2017 Modern Kernel
 */


namespace common\plugins\facebook;

use common\Core;
use common\models\Setting;
use Yii;
use yii\base\Widget;

/**
 * Class SDK
 * @package common\plugins\facebook
 */
class SDK extends Widget
{
    public $appId;

    /**
     * @inheritdoc
     */
    public function init()
    {
        if (empty($this->appId)) {
            $this->appId = Setting::getValue('fbAppId');
        }
        parent::run(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        if (!empty($this->appId)) {
            $this->register();
        }
    }

    /**
     * register SDK
     */
    protected function register()
    {
        $lang=str_replace('-', '_', Yii::$app->language);
        $js = <<<EOB
window.fbAsyncInit = function() {
    FB.init({
        appId: "APP_ID",
        xfbml: true,
        version: "v2.6"
    });
};

(function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) { return; }
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/LANG_ID/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
EOB;
        $js = Core::translateMessage($js, ['APP_ID' => $this->appId, 'LANG_ID' => $lang]);
        $this->view->registerJs($js);
    }
}