<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2016 Modern Kernel
 */

namespace common\bootstrap;


use common\models\Message;
use common\models\Setting;
use Yii;
use yii\base\Component;
use yii\base\Exception;

/**
 * Class Configuration
 * @package common\components
 */
class Configuration extends Component
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        /* language / timezone */
        if (is_a(Yii::$app, '\yii\web\Application')) {
            if (!Yii::$app->user->isGuest) {
                try {
                    $user = Yii::$app->user->identity;

                    /* if user local not exist, set default */
                    $locales = Message::getLocaleList();
                    if (!in_array($user->language, array_keys($locales))) {
                        $user->language = Setting::getValue('language');
                        $user->save();
                    }

                    Yii::$app->language = $user->language;
                    Yii::$app->setTimeZone($user->timezone);
                } catch (Exception $e) {
                    Yii::$app->cache->flush();
                    Yii::$app->db->schema->refresh();
                    Yii::$app->user->logout();
                }
            } else {
                $timezone = Setting::getValue('timezone');
                $language = Setting::getValue('language');
                Yii::$app->language = $language;
                Yii::$app->setTimeZone($timezone);
            }
        }

        /* other site settings */
        // mail
        $mailProtocol = Setting::getValue('mailProtocol');
        if ($mailProtocol == 'smtp') {
            $host = Setting::getValue('smtpHost');
            $user = Setting::getValue('smtpUsername');
            $pass = Setting::getValue('smtpPassword');
            $port = Setting::getValue('smtpPort');
            $encryption = Setting::getValue('smtpEncryption');
            Yii::$container->set('yii\swiftmailer\Mailer', [
                //'class' => 'yii\swiftmailer\Mailer',
                'viewPath' => '@common/mail',
                'useFileTransport' => false,
                'transport' => [
                    'class' => 'Swift_SmtpTransport',
                    'host' => $host,
                    'username' => $user,
                    'password' => $pass,
                    'port' => $port,
                    'encryption' => $encryption
                ],
            ]);
        }

        // recaptcha
        $rcKey = Setting::getValue('reCaptchaKey');
        $rcSecret = Setting::getValue('reCaptchaSecret');
        if (!empty($rcKey) && !empty($rcSecret)) {
            Yii::$container->set('himiklab\yii2\recaptcha\ReCaptcha', [
                'siteKey' => $rcKey,
                'secret' => $rcSecret,
            ]);
        }

        // client facebbok
        $clients = [];
        $fbAppId = Setting::getValue('facebookAppId');
        $fbAppSecret = Setting::getValue('facebookAppSecret');
        if (!empty($fbAppId) && !empty($fbAppSecret)) {
            $clients['facebook'] = [
                'class' => 'yii\authclient\clients\Facebook',
                'clientId' => $fbAppId,
                'clientSecret' => $fbAppSecret,
            ];
        }
        // client google
        $gClientId = Setting::getValue('googleClientId');
        $gClientSecret = Setting::getValue('googleClientSecret');
        if (!empty($gClientId) && !empty($gClientSecret)) {
            $clients['google'] = [
                'class' => 'yii\authclient\clients\Google',
                'clientId' => $gClientId,
                'clientSecret' => $gClientSecret,
            ];
        }
        // clients OK
        if (!empty($clients)) {
            Yii::$container->set('yii\authclient\Collection', [
                'class' => 'yii\authclient\Collection',
                'clients' => $clients,
            ]);
        }


        // Auth APIS

        /* END: other site settings */


        /* Header */
        //$headers = Yii::$app->response->headers;

        // HSTS
        //$headers->add('strict-transport-security', 'max-age=600');
        //\Yii::$app->

        /* not cmd */
        if (!is_a(Yii::$app, 'yii\console\Application')) {
            //$module = \Yii::$app->getModule('debug');
            //$module->allowedIPs=['127.0.0.1', '::1'];
            //$module->allowedIPs = [''];
        }


        //\Yii::$app->view->theme->skin='skin-green';
        //$a=Account::find()->one();
//        \Yii::$container->set('modernkernel\themeadminlte\AdminlteTheme', [
//            'skin' => 'skin-green'.$a->id,
//        ]);

//        \Yii::$container->set('yii\web\JqueryAsset', [
//            'sourcePath'=>null,
//            'js' => ['https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js']
//        ]);
    }

}