<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2016 Modern Kernel
 */

namespace common\bootstrap;


use Yii;
use yii\base\Component;
use yii\base\Exception;

/**
 * Class Setting
 * @package common\components
 */
class Setting extends Component
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        /* user settings */
        if (is_a(Yii::$app, '\yii\web\Application')) {
            if (!Yii::$app->user->isGuest) {
                try {
                    $user = Yii::$app->user->identity;
                    Yii::$app->language = $user->language;
                    Yii::$app->setTimeZone($user->timezone);
                } catch (Exception $e) {
                    Yii::$app->cache->flush();
                    Yii::$app->db->schema->refresh();
                    Yii::$app->user->logout();
                }

            }
        }

        /* Header */
        //$headers = Yii::$app->response->headers;

        // HSTS
        //$headers->add('strict-transport-security', 'max-age=600');
        //\Yii::$app->

        /* not cmd */
        if (!is_a(Yii::$app, 'yii\console\Application')) {
            $module = \Yii::$app->getModule('debug');
            //$module->allowedIPs=['127.0.0.1', '::1'];
            $module->allowedIPs = [''];
        }


        //\Yii::$app->view->theme->skin='skin-green';
        //$a=Account::find()->one();
//        \Yii::$container->set('modernkernel\themeadminlte\AdminlteTheme', [
//            'skin' => 'skin-green'.$a->id,
//        ]);

//        \Yii::$container->set('yii\web\JqueryAsset', [
//            'sourcePath'=>null,
//            'js' => ['https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js']
//        ]);
    }

}