<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2016 Modern Kernel
 */

namespace common\components;


use yii\base\Component;

/**
 * Class Setting
 * @package common\components
 */
class Setting extends Component
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        /* Header */
        //$headers = Yii::$app->response->headers;

        // HSTS
        //$headers->add('strict-transport-security', 'max-age=600');
    }

}