<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2016 Modern Kernel
 */

namespace frontend\widgets;


use common\models\Setting;
use yii\base\Widget;

/**
 * Class Adsense
 * @package frontend\widgets
 */
class Adsense extends Widget
{
    /**
     * @inheritdoc
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $adsense=Setting::getValue('adsense');
        if(!empty($adsense)){
            $js=<<<EOB
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Responsive -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="{$adsense}"
     data-ad-slot="2560515712"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
EOB;
            echo $js;

        }
    }
}