<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2016 Power Kernel
 */

namespace frontend\widgets;


use common\models\Setting;
use Yii;
use yii\base\Widget;
use yii\helpers\Html;
use yii\web\View;

/**
 * Class Adsense
 * @package frontend\widgets
 */
class Adsense extends Widget
{

    public $adClient = '';

    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();
        if (empty($this->adClient)) {
            $this->adClient = Setting::getValue('adsense');
        }

    }

    /**
     * @inheritdoc
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        if (empty($this->adClient)) {
            return null;
        }

        $this->registerUnitAds();
        return Html::tag('ins', '', [
            'class' => 'adsbygoogle',
            'style' => 'display:block',
            'data-ad-client' => $this->adClient,
            'data-ad-slot' => '2560515712',
            'data-ad-format' => 'auto'
        ]);

    }

    /**
     * register unit ads
     */
    protected function registerUnitAds()
    {
        $this->registerJsFile();
        $js = '(adsbygoogle = window.adsbygoogle || []).push({});';
        Yii::$app->view->registerJs($js, View::POS_END);
    }

    /**
     * register js file
     */
    protected function registerJsFile()
    {
        Yii::$app->view->registerJsFile(
            '//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js',
            ['position' => View::POS_HEAD, 'async' => true]
        );
    }
}
