<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2016 Power Kernel
 */


namespace frontend\widgets;


use common\models\Setting;
use yii\base\Widget;

/**
 * Class AmzAds
 * @package frontend\widgets
 */
class AmzAds extends Widget
{
    /**
     * @inheritdoc
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $tracking = Setting::getValue('amzTracking');
        $nativeAds = Setting::getValue('amzAds');
        if (!empty($tracking) && !empty($nativeAds)) {
            return $this->render('amzAds', ['tracking' => $tracking, 'nativeAds'=>$nativeAds]);
        }

    }
}