<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2016 Modern Kernel
 */


namespace frontend\widgets;


use common\models\Setting;
use yii\base\Widget;

/**
 * Class AmzAds
 * @package frontend\widgets
 */
class AmzAds extends Widget
{
    /**
     * @inheritdoc
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $code = Setting::getValue('amzAds');
        if (!empty($code)) {
            return $this->render('amzAds', ['code' => $code]);
        }

    }
}