<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2016 Power Kernel
 */


namespace frontend\widgets;


use common\models\Setting;
use yii\base\Widget;

/**
 * Class AmzSearchAds
 * @package frontend\widgets
 */
class AmzSearchAds extends Widget
{
    /**
     * @inheritdoc
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $tracking = Setting::getValue('amzTracking');
        $searchAds = Setting::getValue('amzSearchAds');
        if (!empty($tracking) && !empty($searchAds)) {
            return $this->render('amzSearchAds', ['tracking' => $tracking, 'searchAds'=>$searchAds]);
        }

    }
}