<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2016 Modern Kernel
 */

namespace frontend\widgets;


use common\models\Blog;
use Yii;
use yii\base\Widget;

/**
 * Class BlogPost
 * @package frontend\widgets
 */
class BlogPost extends Widget
{
    public $type = 'mostViewed';
    public $title = '';
    public $models = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->type == 'mostViewed') {
            $this->title = Yii::t('app', 'Most Viewed');
            $this->models = Blog::mostViewed();
        }
        if ($this->type == 'latest') {
            $this->title = Yii::t('app', 'Latest Updates');
            $this->models = Blog::latest();
        }
    }

    /**
     * @inheritdoc
     * @return string
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        if (!empty($this->models)) {
            return $this->render('blogPost', ['models' => $this->models, 'title' => $this->title]);
        }

    }
}