<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2016 Modern Kernel
 */

namespace frontend\widgets;


use yii\base\Widget;

/**
 * Class Footer
 * @package frontend\widgets
 */
class Footer extends Widget
{
    /**
     * @inheritdoc
     * @return string
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('footer');
    }
}