<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2016 Power Kernel
 */

namespace frontend\widgets;


use common\models\Menu;
use Yii;
use yii\base\Widget;

/**
 * Class Footer
 * @package frontend\widgets
 */
class Footer extends Widget
{
    /**
     * @inheritdoc
     * @return string
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $items=Menu::find()->where(['status'=>Menu::STATUS_ACTIVE, 'id_parent'=>null, 'position'=>'footer'])->orderBy('order')->all();
        return $this->render('footer', ['items'=>$items]);
    }
}