<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2016 Modern Kernel
 */

namespace frontend\widgets;


use yii\base\Widget;

/**
 * Class Header
 * @package frontend\widgets
 */
class Header extends Widget
{

    /**
     * @inheritdoc
     * @return string
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('header');
    }
}