<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2016 Modern Kernel
 */

namespace frontend\widgets;


use yii\base\Widget;

class Header extends Widget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('header');
    }
}